version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: projeto-ic-redis
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: ./back-end
    container_name: projeto-ic-backend
    ports:
      - "5000:5000"
    env_file:
      - ./back-end/.env
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build: ./front-end
    container_name: projeto-ic-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge